### ISSUE TITLE
Missing package folder

### ISSUE THREAD

**Issue by andyli** [TiVo/activity#1]
The classes are in the `activity` package, but the hx files are not put inside such folder...
Neither using the haxelib release or using this repo as `-cp` will work...

**Comment by bjitivo** [comment]
Sorry about that.  We keep our sources in Perforce and the transition to git somehow put the code in the wrong directory.  Fixed with commit 95f0ae1ebfdfce4ad544be638e5a20d891c8bf9.

**Comment by andyli** [comment]
I think you need a `classPath` field in "haxelib.json" too. ;)
